# Earth Rover v1p0
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

#  velocity_controller_front_left_wheel:
#    type: velocity_controllers/JointVelocityController
#    joint: front_left_wheel_joint
#    pid: {p: 100, i: 0.01, d: 10.0}

#  velocity_controller_front_right_wheel:
#    type: velocity_controllers/JointVelocityController
#    joint: front_right_wheel_joint
#    pid: {p: 100, i: 0.01, d: 10.0}

  velocity_controller_back_left_wheel:
    type: velocity_controllers/JointVelocityController
    joint: back_left_wheel_joint
    pid: {p: 100, i: 0.01, d: 10.0}

#  velocity_controller_back_right_wheel:
#    type: velocity_controllers/JointVelocityController
#    joint: back_right_wheel_joint
#    pid: {p: 100, i: 0.01, d: 10.0}


  # Skid Steer Controller
  skid_controller:
    type: diff_drive_controller/DiffDriveController

    left_wheel:   [front_left_wheel_joint, back_left_wheel_joint]
    right_wheel:  [front_right_wheel_joint, back_right_wheel_joint] 

    publish_rate: 50
    cmd_vel_timeout: 0.25

    pose_covariance_diagonal: [0.001, 0.001, 100000.0, 100000.0, 100000.0, 0.3]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 100000.0, 100000.0, 0.3]
    
    enable_odom_tf: false
    open_loop: true

    estimate_velocity_from_position: false

    wheel_seperation: 0.85
    wheel_radius: 0.254
    wheel_seperation_multiplier: 1.5
    wheel_radius_multiplier: 1.0

    linear/x/has_velocity_limits: false
    angular/z/has_velocity_limits: false

  ankle_mock_controller:
    type: diff_drive_controller/DiffDriveController

    left_wheel:   [front_left_ankle_joint,back_left_ankle_joint]
    right_wheel:  [front_right_ankle_joint,back_right_ankle_joint] 

    publish_rate: 50
    cmd_vel_timeout: 0.25

    pose_covariance_diagonal: [0.001, 0.001, 100000.0, 100000.0, 100000.0, 0.3]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 100000.0, 100000.0, 0.3]
    
    enable_odom_tf: false
    open_loop: true

    estimate_velocity_from_position: false

    wheel_seperation: 0.85
    wheel_radius: 0.254
    wheel_seperation_multiplier: 1.5
    wheel_radius_multiplier: 1.0

    linear/x/has_velocity_limits: false
    angular/z/has_velocity_limits: false

  ankle_fl_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_left_ankle_joint
    pid:
        p: 10.0
        i: 1
        d: 1
