# Earth Rover v1p0
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # not connected
  velocity_controller_front_left_wheel:
    type: velocity_controllers/JointVelocityController
    joint: back_left_drive_wheel
    pid: {p: 100, i: 0.01, d: 10.0}

  # not connected
  velocity_controller_front_right_wheel:
    type: velocity_controllers/JointVelocityController
    joint: back_right_drive_wheel
    pid: {p: 100, i: 0.01, d: 10.0}

  velocity_controller_back_left_wheel:
    type: velocity_controllers/JointVelocityController
    joint: back_left_drive_wheel
    pid: {p: 100, i: 0.01, d: 10.0}

  # not connected 
  velocity_controller_back_right_wheel:
    type: velocity_controllers/JointVelocityController
    joint: back_right_drive_wheel
    pid: {p: 100, i: 0.01, d: 10.0}


  # Skid Steer Controller
  robot_controller:
    type: diff_drive_controller/DiffDriveController

    left_wheel:   [front_left_drive_wheel, back_left_drive_wheel]
    right_wheel:  [front_right_drive_wheel, back_right_drive_wheel] 

    publish_rate: 50
    cmd_vel_timeout: 0.25

    pose_covariance_diagonal: [0.001, 0.001, 100000.0, 100000.0, 100000.0, 0.3]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 100000.0, 100000.0, 0.3]
    
    enable_odom_tf: false
    open_loop: true

    estimate_velocity_from_position: false

    wheel_seperation: 0.85
    wheel_radius: 0.254
    wheel_seperation_multiplier: 1.525
    wheel_radius_multiplier: 1.0

    linear/x/has_velocity_limits: false
    angular/z/has_velocity_limits: false
